### PR TITLE
Fix HashPipe to not fail in configure if an authAlias is used

### LINKED ISSUE #10423: Hash pipe no longer works with a secret stored in an authalias
### Current Behavior

in 9.4 this pipe doesn't work anymore:

			<pipe name="hmacHash" className="org.frankframework.pipes.HashPipe"
				getInputFromSessionKey="fileContents"
				storeResultInSessionKey="hashResult"
				charset="ISO8859_1"
				hashEncoding="Hex">
				<param name="authAlias" value="${current.node.name}/${current.server.name}_HMAC_Close"/>
				<forward name="success" path="processRecords" />
			</pipe>

Exception configuring HashPipe [hmacHash]: When using a (h)mac based Algorithm, using a secret is mandatory

Code handling the authalias seems to be lost in the refactor(according to Niels)

### Expected Behavior

I should be able to get a hash secret out of an authalias

### Environment Information

**FF! 9.4.0**: ibis4sapcd 
Running on **LPCENL005087420** using **Apache Tomcat/10.1.50**
Java Version: **OpenJDK Runtime Environment (25.0.1+8-LTS)**
Heap size: **287.0 MiB**, total JVM memory: **408.0 MiB**
Free memory: **121.0 MiB**, max memory: **1.0 GiB**
Free disk space: **24.1 GiB**, total disk space: **237.4 GiB**
Up since: **2026-02-11 10:00:17**, timezone: **Europe/Paris**

### Steps To Reproduce

_No response_

### Configuration

```xml
<pipe name="hmacHash" className="org.frankframework.pipes.HashPipe"
				getInputFromSessionKey="fileContents"
				storeResultInSessionKey="hashResult"
				charset="ISO8859_1"
				hashEncoding="Hex">
				<param name="authAlias" value="${current.node.name}/${current.server.name}_HMAC_Close"/>
				<forward name="success" path="processRecords" />
			</pipe>
```

### Input

_No response_

### What database are you using?

_No response_

### What browsers are you seeing the problem on?

_No response_

### Relevant Log Output

```console

```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by evandongen**
closes #10423

### CODE REVIEW

File: core/src/main/java/org/frankframework/pipes/HashPipe.java [hunk 1]
```diff
@@ -100,11 +99,16 @@ public void configure() throws ConfigurationException {
 
 		super.configure();
 
-		if (algorithm.isSecretRequired() && (secret == null && !getParameterList().hasParameter("secret"))) {
-			throw new ConfigurationException("When using a (h)mac based Algorithm, using a secret is mandatory");
+		if (algorithm.isSecretRequired() && !isSecretOrAuthAliasDefined()) {
```
Comment (evandongen) [inline core/src/main/java/org/frankframework/pipes/HashPipe.java:102]: When using an authAlias, which can contain a secret as well, a `ConfigurationException` was thrown. The behaviour is now similar to 8.2, before the hashPipe got a `configure()` method

File: core/src/main/java/org/frankframework/pipes/HashPipe.java [hunk 2]
```diff
@@ -100,11 +99,16 @@ public void configure() throws ConfigurationException {
...
+			throw new ConfigurationException("When using a (h)mac based Algorithm, using a secret or authAlias is mandatory");
 		}
 	}
 
+	private boolean isSecretOrAuthAliasDefined() {
```
Comment (evandongen) [inline core/src/main/java/org/frankframework/pipes/HashPipe.java:107]: To keep it readable, i moved this to a seperate method
