### PR TITLE
Do not show Save button in Larva when saving is not possible

### LINKED ISSUE #7720: larva save and windiff button not working
### Current Behavior

could be due to the new framework version and authentication methods?

i used 
# Disable login on console and ladybug endpoints for initial testing needs to be updated
application.security.console.authentication.type=NONE
application.security.testtool.authentication.type=NONE

image

### Expected Behavior

working buttons

### Environment Information

**FF! 9.0.0-20241018.042327**: frank2logex 
Running on **LAPTOP-GNUACE2** using **Apache Tomcat/10.1.24**
Java Version: **OpenJDK Runtime Environment (21.0.2+13-LTS)**
Heap size: **281.2 MiB**, total JVM memory: **359.0 MiB**
Free memory: **77.8 MiB**, max memory: **1.0 GiB**
Free disk space: **788.0 GiB**, total disk space: **952.8 GiB**

### Steps To Reproduce

_No response_

### Configuration

_No response_

### Input

_No response_

### What database are you using?

_No response_

### What browsers are you seeing the problem on?

_No response_

### Relevant Log Output

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by tnleeuw**
## Changes

When saving the actual results of a step in a Larva is not possible on the environment, or because the step is an inline step, do not show the Save / Windiff buttons and instead show a text message explaining why.

<details>
<summary>
<strong>Pull Request Checklist</strong>
</summary>
  
### Title

- [x] Title expresses the business value (who benefits + what outcome)

### Issues

- [x] Closes #7720

### Backports

- [x] N/A

### Documentation

- [x] FF! Doc updated (user-facing behavior/config) (N/A)
- [x] FF! Manual updated (if applicable) (N/A)
- [x] Javadoc updated/generated (developer-facing APIs) (N/A)

### Tests

- [ ] Unit tests added/updated
- [x] E2E/Integration tests added/updated (if applicable) (N/A)

### Breaking changes

- [x] Breaking change recorded in markdown file
- [x] Migration notes included (if needed)
</details>

### CODE REVIEW

File: larva/src/main/java/org/frankframework/larva/LarvaConfig.java [hunk 1]
```diff
@@ -37,13 +37,14 @@ public class LarvaConfig {
...
-	private @Getter @Setter boolean autoSaveDiffs = AppConstants.getInstance().getBoolean("larva.diffs.autosave", false);
+	private @Getter @Setter boolean enableSaving = AppConstants.getInstance().getBoolean("servlet.LarvaServlet.allowFileSave", false);
+	private @Getter @Setter boolean autoSaveDiffs = enableSaving && AppConstants.getInstance().getBoolean("larva.diffs.autosave", false);
 
 	/**
 	 * if allowReadlineSteps is set to true, actual results can be compared in line by using .readline steps.
 	 * Those results cannot be saved to the expected value defined inline, however.
 	 */
-	private @Getter @Setter boolean allowReadlineSteps = false;
+	private @Getter @Setter boolean allowReadlineSteps = true;
```
Comment (tnleeuw) [inline larva/src/main/java/org/frankframework/larva/LarvaConfig.java:47]: I think we can enable readline-steps safely; the "Save" button was already disabled for readline-steps and now we also display a message for the user to explain why saving is not possible for a given failed step.
