### PR TITLE
Show a console warning when the XmlValidator pipe is in an incorrect state.

### LINKED ISSUE #6800: Show configuration warning/exception when Json2XmlValidator is configured with throwException=true and has a failure forward defined
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
FrankDoc states the following:
image

It would a nice addition to give a configuration warning/exception indicating that the failure forward is ignored when a failure forward is defined and the Json2XmlValidator is configured with `throwException="true"`.

**Reporter**
Laurens

### PR DESCRIPTION
**Pull request by thomaspj10**
Closes #6800 

Shows a configuration warning when the XmlValidator is in an incorrect state (failure forward and `throwException=true`).

The setup of the tests adds both forwards and set `throwException=true`, so some asserts had to be modified.

### CODE REVIEW

File: core/src/test/java/org/frankframework/pipes/XmlValidatorPipelineTest.java [hunk 1]
```diff
@@ -192,7 +192,7 @@ void testStoreRootElement(Class<AbstractXmlValidator> implementation) throws Exc
 		validator.start();
 
 		// Assert
-		assertNoWarnings(configuration);
+		assertWarnings(configuration, 1);
```
Comment (nielsm5) [inline core/src/test/java/org/frankframework/pipes/XmlValidatorPipelineTest.java:195]: I saw in `buildXmlValidator(...)` a method call `createFailureForward()` perhaps you could remove that line, and make a specific test when adding it, that you will see 1 warning opposed to 0 😃

**Review by nielsm5 — CHANGES_REQUESTED** [review]

**Review by nielsm5 — APPROVED** [review]
Ik snap hem helemaal! Misschien dat het verschil tussen de tests met throwException en useFailureForward iets explicieter kunnen (in de test het aanzetten ipv uitzetten van de tegenhanger). Maar verder prima!

**Review by evandongen — APPROVED** [review]
