### PR TITLE
Fix AOP config for ladybug

### LINKED ISSUE #10734: Ladybug does not display senders (Pointcut parser rejected expression)
``` 
2026-04-21 12:12:14,071 DEBUG [main] aspectj.AspectJExpressionPointcut - Pointcut parser rejected expression [      execution(       *       org.frankframework.core.ISender.sendMessage(        org.frankframework.stream.Message,        org.frankframework.core.PipeLineSession       )      )      and      args(message, session)      ]: java.lang.IllegalArgumentException: warning no match for this type name: session [Xlint:invalidAbsoluteTypeName]
2026-04-21 12:12:14,076 DEBUG [main] aspectj.AspectJExpressionPointcut - Pointcut parser rejected expression [      execution(       *       org.frankframework.core.ISender.sendMessageOrThrow(        org.frankframework.stream.Message,        org.frankframework.core.PipeLineSession       )      )      and      args(message, session)      ]: java.lang.IllegalArgumentException: warning no match for this type name: session [Xlint:invalidAbsoluteTypeName]
2026-04-21 12:12:14,083 DEBUG [main] aspectj.AspectJExpressionPointcut - Pointcut parser rejected expression [      execution(       *       org.frankframework.core.IBlockEnabledSender+.sendMessage(        *,        org.frankframework.stream.Message,        org.frankframework.core.PipeLineSession       )      )      and      args(blockHandle, message, session)      ]: java.lang.IllegalArgumentException: warning no match for this type name: session [Xlint:invalidAbsoluteTypeName]
2026-04-21 12:12:14,089 DEBUG [main] aspectj.AspectJExpressionPointcut - Pointcut parser rejected expression [      execution(       *       org.frankframework.processors.CacheSenderWrapperProcessor.sendMessage(        org.frankframework.senders.AbstractSenderWrapper,        org.frankframework.stream.Message,        org.frankframework.core.PipeLineSession       )      )      and      args(abstractSenderWrapper, message, session)      ]: java.lang.IllegalArgumentException: warning no match for this type name: abstractSenderWrapper [Xlint:invalidAbsoluteTypeName]
2026-04-21 12:12:14,095 DEBUG [main] aspectj.AspectJExpressionPointcut - Pointcut parser rejected expression [      execution(       *       org.frankframework.processors.CoreListenerProcessor.getMessage(        org.frankframework.core.ICorrelatedPullingListener,        String,        org.frankframework.core.PipeLineSession       )      )      and      args(listener, correlationID, pipeLineSession)      ]: java.lang.IllegalArgumentException: warning no match for this type name: correlationID [Xlint:invalidAbsoluteTypeName]

```

### PR DESCRIPTION
**Pull request by nielsm5**
Unfortunatelly I had to duplicate (and improve) the TestAppender code. But we now have a test to prevent this from happening again 😄.

It is still possible some classes are not pointcut due to AOP being disabled for example. I had to explicitly enable it in the pipeline config... At least right now we will know when the arguments don't match.

### CODE REVIEW

File: core/src/main/java/org/frankframework/processors/ListenerProcessor.java [hunk 1]
```diff
@@ -26,6 +26,6 @@
  */
 public interface ListenerProcessor<M> {
 
-	Message getMessage(ICorrelatedPullingListener<M> listener, String correlationID, PipeLineSession pipeLineSession) throws ListenerException, TimeoutException;
+	Message getMessage(ICorrelatedPullingListener<M> listener, String correlationId, PipeLineSession pipeLineSession) throws ListenerException, TimeoutException;
```
Comment (evandongen) [inline core/src/main/java/org/frankframework/processors/ListenerProcessor.java:29]: Hopelijk gaat aop hier niet op mis! 😄

**Review by evandongen — APPROVED** [review]

File: core/src/main/java/org/frankframework/processors/ListenerProcessor.java (hunk 1 above)
Comment (nielsm5) [reply core/src/main/java/org/frankframework/processors/ListenerProcessor.java:29]: Haha, nu niet meer!
