### PR TITLE
Fix Locker expiryDate not working as expected and add unit test

### LINKED ISSUE #9818: Locker unit test (9.3)
Tim encountered a problem with a change from #8652: Locker.java was broken because of this.

The changed value of Instant is not used. We need a unit test to prove this doesn't work as expected, so we can fix that.

See https://github.com/frankframework/frankframework/commit/d6094df407092e10abae85475da2bdbafc3d6d77#diff-e54cc68613d6d088bafe86b56f8bafd16b722ee5f2273a528dd927cf553bb185R184

### PR DESCRIPTION
**Pull request by evandongen**
## Changes
Locker.java wasn't working as intended. Now fixed, with a unit test to prove it. closes #9818 

<details>
<summary>
<strong>Pull Request Checklist</strong>
</summary>
  
### Title

- [x] Title expresses the business value (who benefits + what outcome)

### Issues

- [x] Relevant issues linked

### Backports

- [ ] Backport PRs created (if needed) and linked

Backports will be created for 9.3.1 if this is approved.

### Documentation

No changes needed, this was a bug.

### Tests

- [x] Unit tests added/updated
- [n/a] E2E/Integration tests added/updated (if applicable)

### Breaking changes

No breaking changes.
</details>

### CODE REVIEW

File: core/src/main/java/org/frankframework/util/Locker.java [hunk 1]
```diff
@@ -175,16 +187,12 @@ public String acquire(MessageKeeper messageKeeper) throws JdbcException, SQLExce
...
+					stmt.setString(2, getType().name());
+					stmt.setString(3, Misc.getHostname());
 					stmt.setTimestamp(4, Timestamp.from(instant));
 
-					if (getType() == LockType.T) {
-						instant.plus(getRetention(), ChronoUnit.HOURS);
-					} else {
-						instant.plus(getRetention(), ChronoUnit.DAYS);
-					}
+					instant = instant.plus(getRetention(), getType().getChronoUnit());
```
Comment (tnleeuw) [inline core/src/main/java/org/frankframework/util/Locker.java]: I would prefer to have a 2nd `Instant expiry` here.

File: core/src/main/java/org/frankframework/util/Locker.java [hunk 2]
```diff
@@ -245,14 +254,17 @@ public void release(String objectIdWithSuffix) throws JdbcException, SQLExceptio
 		if (LOCK_IGNORED.equals(objectIdWithSuffix)) {
 			log.info("lock not set, ignoring unlock");
 		} else {
-			if (getType()==LockType.T) {
+			if (LockType.T.equals(getType())) {
```
Comment (tnleeuw) [inline core/src/main/java/org/frankframework/util/Locker.java]: You don't need `.equals()` for enum types.

File: core/src/main/java/org/frankframework/util/Locker.java [hunk 3]
```diff
@@ -99,32 +99,43 @@ public class Locker extends JdbcFacade implements HasTransactionAttribute {
...
+		@Getter
+		private final int getDefaultRetention;
+
+		@Getter
+		private final ChronoUnit chronoUnit;
+
+		LockType(int getDefaultRetention, ChronoUnit chronoUnit) {
+			this.getDefaultRetention = getDefaultRetention;
+			this.chronoUnit = chronoUnit;
+		}
```
Comment (tnleeuw) [inline core/src/main/java/org/frankframework/util/Locker.java:117]: 👌

**Review by tnleeuw — APPROVED** [review]

**Review by tnleeuw — APPROVED** [review]
