### PR TITLE
Move success forward to FixedResultPipe

### LINKED ISSUE #7679: Success en exception forwards onderbrengen in FixedForwardPipe ipv AbstractPipe
Tijdens implementatie van de 'forPipe' kwamen we erachter dat 'succes' en 'exception', die we hier niet gebruiken wel beschikbaar zijn op deze pipe. Om dit (met het oog op de Frank Flow) op te lossen zouden we de forwards moeten herschikken: 

De success en exception forwards zitten op AbstractPipe, dus er zijn meer pipes die hier last van hebben, zoals bijvoorbeeld XmlIf en RegExPipe. Die forwards naar FixedForwardPipe schuiven en alle pipes die een alternatieve flow hebben AbstractPipe laten gebruiken is de oplossing.

Zie ook #7609

### PR DESCRIPTION
**Pull request by thomaspj10**
Closes #7679

### CODE REVIEW

File: core/src/test/java/org/frankframework/core/PipeLineTest.java [hunk 1]
```diff
@@ -242,13 +242,11 @@ public void testNonFixedForwardPipesWithNoForwardToNextPipe() throws Configurati
```
Comment (thomaspj10) [inline core/src/test/java/org/frankframework/core/PipeLineTest.java:242]: The name of this test and the actual functionality did not line up.

**Review by evandongen — APPROVED** [review]

**Review by nielsm5 — APPROVED** [review]
