### PR TITLE
Add an example to the DirectoryListener and fix an incorrect reference.

### LINKED ISSUE #7219: MessageType in FileSystemListener schould be a enum (and contents should be content)
### Current Behavior

The documentation of the directory listener is not very clear

### Expected Behavior

Possible improvements
- Make the message Type an enum instead of a string.
- The name MessageType is not very descriptive for what it does. 
- The meaning of content and contents is very clos to each other but in my opinion it should be content of filecontent
- example in the frankdoc would be welcome
### Environment Information

ff 8.2.0

### Steps To Reproduce

https://frankdoc.frankframework.org/#/Listeners/DirectoryListener

### Configuration

_No response_

### Input

_No response_

### What database are you using?

_No response_

### What browsers are you seeing the problem on?

_No response_

### Relevant Log Output

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by thomaspj10**
Closes #7219 

The usage of a DirectoryListener is vague at the moment. I added a clear example to the documentation. Read #7219 on why not every point is implemented.

### CODE REVIEW

File: filesystem/src/main/java/org/frankframework/receivers/DirectoryListener.java [hunk 1]
```diff
@@ -21,6 +21,25 @@
 import org.frankframework.filesystem.FileSystemListener;
 import org.frankframework.filesystem.LocalFileSystem;
 
+/**
+ * Listener that looks in a FileSystem for files. <code>messageType</code> dictates what information of the file is passed in the message.
```
Comment (nielsm5) [inline filesystem/src/main/java/org/frankframework/receivers/DirectoryListener.java:25]:
```suggestion
 * Listener that looks for files in a LocalFileSystem. The DirectoryListener keeps track of the file process by storing it in different folders. The application may create the folders if you (a) set the <code>root</code> attribute and (b) set the attribute <code>createFolders</code> to true.
 
 The attribute <code>messageType</code> dictates what information of the file is passed to the pipeline. This may be the name, canonical path, the entire file, or the file's metadata.
```

**Review by nielsm5 — COMMENTED** [review]
Issue #7219 talks about the possibility to turn messageType into an enum, I think that would simplify the use of this listener. Both functionally for the Frank!Developers as well as technically (see below code block).


```
			if (StringUtils.isEmpty(getMessageType()) || getMessageType().equalsIgnoreCase("name")) {
				return new Message(getFileSystem().getName(file));
			}
			if (StringUtils.isEmpty(getMessageType()) || getMessageType().equalsIgnoreCase("path")) {
				return new Message(getFileSystem().getCanonicalName(file));
			}
			if (getMessageType().equalsIgnoreCase("contents")) {
				return getFileSystem().readFile(file, getCharset());
			}
			if (getMessageType().equalsIgnoreCase("info")) {
				return new Message(FileSystemUtils.getFileInfo(getFileSystem(), file, getOutputFormat()));
			}
```

**Comment by thomaspj10** [comment]
I didn't like my old implementation of making the `methodType` an Enum, but I think I managed to come up with a nice solution after all. The interface `IMessageType` is required because there are actually two different Enum interfaces required for DirectoryListener (and a few others) and MailListener. This way they both have a different enum, while still working correctly with their parent class.

File: filesystem/src/main/java/org/frankframework/filesystem/FileSystemListener.java [hunk 2]
```diff
@@ -304,28 +317,25 @@ public Message extractMessage(@Nonnull RawMessageWrapper<F> rawMessage, @Nonnull
...
+				case "ATTRIBUTE", "HEADER" -> {
+					Map<String,Object> attributes = getFileSystem().getAdditionalFileProperties(file);
+					if (attributes != null) {
+						Object result = attributes.get(getSearchKey());
+						if (result != null) {
+							yield Message.asMessage(result);
+						}
+					}
+					log.warn("no attribute [{}] found for file [{}]", getMessageType(), getFileSystem().getName(file));
+					yield null;
```
Comment (nielsm5) [inline filesystem/src/main/java/org/frankframework/filesystem/FileSystemListener.java:335]: Dit mag er uit hoor. Slaat nergens op om een attribute ergens uit te halen dat in `INFO` zit. Dan moet men maar een xpath oid doen.

Comment (nielsm5) [reply filesystem/src/main/java/org/frankframework/filesystem/FileSystemListener.java:335]: Ik zie dat je dan wel info in het mail fs moet zetten. Ik weet niet of daar al tests voor zijn. Ik ga er van uit dat `FileSystemUtils.getFileInfo` ook gewoon werkt voor het mailfilesystem. (En daar zitten de 'additionalProperties' in.)

Comment (nielsm5) [reply filesystem/src/main/java/org/frankframework/filesystem/FileSystemListener.java:335]: De releases.md heb ik in https://github.com/frankframework/frankframework/pull/7290 aangemaakt. Maar dat is nog niet gemerged (dus je hebt er nog niet veel aan).

Comment (thomaspj10) [reply filesystem/src/main/java/org/frankframework/filesystem/FileSystemListener.java]: Dus nog eventjes wachten tot jouw issue op master staat

File: filesystem/src/main/java/org/frankframework/receivers/ExchangeMailListener.java [hunk 3]
```diff
@@ -30,7 +30,7 @@
 import org.frankframework.filesystem.MailListener;
 
 /**
- * Microsoft Exchange Implementation of a {@link MailListener}.
+ * Microsoft Exchange Implementation of a {@link ImapListener}.
```
Comment (tnleeuw) [inline filesystem/src/main/java/org/frankframework/receivers/ExchangeMailListener.java:33]: This doesn't look correct?

File: test/src/main/configurations/FileHandling/Configuration_MFH.xml [hunk 4]
```diff
@@ -12,7 +12,7 @@
 				minStableTime ="${mfh.flow1.minstabletime}"
 				fileTimeSensitive="true"
 				name="MFHIn"
-				messageType="info"
+				messageType="INFO"
```
Comment (tnleeuw) [inline test/src/main/configurations/FileHandling/Configuration_MFH.xml:15]: If using an enum means the value now has to be uppercase then that is another backwards incompatible change.

But doesn't the configuration parser automatically parse enums case-insensitive?

(Backwards incompatible changes shouldn't be in minor releases, right?)

File: filesystem/src/main/java/org/frankframework/receivers/ExchangeMailListener.java (hunk 3 above)
Comment (thomaspj10) [reply filesystem/src/main/java/org/frankframework/receivers/ExchangeMailListener.java:33]: Clicking on the link results in a "Error loading Frank!Element" page (https://frankdoc.frankframework.org/#/All/ExchangeMailListener). But I see that it is not entirely true that this pipe is an implementation of an ImapListener.

Comment (tnleeuw) [reply filesystem/src/main/java/org/frankframework/receivers/ExchangeMailListener.java:33]: It is indeed not an ImapListener. The error is because no Frank!Doc is generated for the MailListener class, but since it's a `{@link ...}` there is still a link.

I think that it doesn't make sense for the Frank!Doc to have documentation pages for abstract classes that Frank! developers cannot use in their configurations, so it is probably best to just rephrase this.

```suggestion
 * Microsoft Exchange Implementation of a mail filesystem.
```

File: test/src/main/configurations/FileHandling/Configuration_MFH.xml (hunk 4 above)
Comment (thomaspj10) [reply test/src/main/configurations/FileHandling/Configuration_MFH.xml:15]: I tested a lowercase enum locally and it seems to work correctly, so that is backwards compatible. The only breaking change is the one mentioned above where I removed the posibility to get attributes or headers based on a search key.

Comment (tnleeuw) [reply test/src/main/configurations/FileHandling/Configuration_MFH.xml:15]: Thanks, I wanted to make sure of this.

The one change mentioned above that is breaking, I think that it something we can get away with in practice because I don't think that anyone actually uses any of the other possible values.

File: filesystem/src/main/java/org/frankframework/receivers/ExchangeMailListener.java (hunk 3 above)
Comment (thomaspj10) [reply filesystem/src/main/java/org/frankframework/receivers/ExchangeMailListener.java:33]: Agreed. The suggestion seems good to me

File: filesystem/src/main/java/org/frankframework/filesystem/FileSystemListener.java [hunk 5]
```diff
@@ -529,14 +526,6 @@ public void setOverwrite(boolean overwrite) {
...
 	}
 
-	/**
-	 * Determines the contents of the message that is sent to the pipeline. Can be 'name', for the filename, 'path', for the full file path, 'contents' for the contents of the file, 'info' for file information. For any other value, the attributes of the file are searched and used
-	 * @ff.default path
-	 */
-	public void setMessageType(String messageType) {
-		this.messageType = messageType;
-	}
-
```
Comment (nielsm5) [inline filesystem/src/main/java/org/frankframework/filesystem/FileSystemListener.java:539]: Deze moet je wel laten staan (met enum param) zodat de JavaDoc in de FrankDoc komt :)

File: filesystem/src/main/java/org/frankframework/receivers/FtpFileSystemListener.java [hunk 6]
```diff
@@ -27,4 +27,12 @@ public FtpFileSystem createFileSystem() {
 		return FtpFileSystemDelegator.super.createFileSystem();
 	}
 
+	/**
+	 * Determines the contents of the message that is sent to the pipeline. The value of the attribute matching the searchKey is returned when using <code>ATTRIBUTE</code>
+	 * @ff.default PATH
+	 */
+	public void setMessageType(MessageType messageType) {
```
Comment (nielsm5) [inline filesystem/src/main/java/org/frankframework/receivers/FtpFileSystemListener.java:34]: Hier kan je dan de ReferTo Gebruiken.

File: filesystem/src/main/java/org/frankframework/receivers/Samba2Listener.java [hunk 7]
```diff
@@ -27,4 +27,12 @@ protected Samba2FileSystem createFileSystem() {
 		return new Samba2FileSystem();
 	}
 
+	/**
+	 * Determines the contents of the message that is sent to the pipeline. The value of the attribute matching the searchKey is returned when using <code>ATTRIBUTE</code>
+	 * @ff.default PATH
+	 */
+	public void setMessageType(MessageType messageType) {
```
Comment (nielsm5) [inline filesystem/src/main/java/org/frankframework/receivers/Samba2Listener.java:34]: Hier kan je dan de ReferTo Gebruiken.

File: filesystem/src/main/java/org/frankframework/receivers/SftpFileSystemListener.java [hunk 8]
```diff
@@ -27,4 +27,12 @@ public SftpFileSystem createFileSystem() {
 		return SftpFileSystemDelegator.super.createFileSystem();
 	}
 
+	/**
+	 * Determines the contents of the message that is sent to the pipeline. The value of the attribute matching the searchKey is returned when using <code>ATTRIBUTE</code>
+	 * @ff.default PATH
+	 */
+	public void setMessageType(MessageType messageType) {
```
Comment (nielsm5) [inline filesystem/src/main/java/org/frankframework/receivers/SftpFileSystemListener.java:34]: Hier kan je dan de ReferTo Gebruiken.

**Review by nielsm5 — CHANGES_REQUESTED** [review]
Vergeet de RELEASES.MD niet 😉

File: filesystem/src/main/java/org/frankframework/filesystem/FileSystemListener.java (hunk 5 above)
Comment (thomaspj10) [reply filesystem/src/main/java/org/frankframework/filesystem/FileSystemListener.java:539]: Ik heb deze verwijderd, omdat deze class geërfd wordt door twee soorten listeners die beide een andere enum nodig hebben (MailListener vs Directory, (s)Ftp en Samba Listeners). Deze functie laten staan kan niet, omdat de children de signature van de functie moeten aanpassen (omdat het 2 verschillende enums zijn). Vandaar dat ik deze functie naar de children heb gekopieerd.

**Review by nielsm5 — APPROVED** [review]
